#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html/
echo 'Hello World!' | sudo tee /var/www/html/index.html
# sudo cp /etc/nginx/sites-enabled/default  /etc/nginx/sites-enabled/default.bak
SERVERCONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"
echo "$SERVERCONFIG" | sudo tee /etc/nginx/sites-enabled/default 
sudo service nginx restart
