#!/usr/bin/env bash

ssh ubuntu@52.86.233.213 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUA0cOosgNUVRU5MURP5M+Jd7/8E9+gqGJrWFewvbVjTm6vuq3LfCEI34Lslt/fwvzqWFdBU1Brqs6uA1tgYHpbj9jkZ9QQjqhWBm7UYStKJhR26gav1NM5JcaPAAZcTIICr91FVShG5cGQVNMw8HiOmTtGRoH7bxpo5Kr7vrNnfBwYcHVDI+gE6/5sE32X8EDaE7Bv5/8SikL5dtp6IPIYx5Kvx8h+vzpaxylxZcYO/SQ4WKcpy8SZr9H367l+CF5zW0rgrJQSIeTVxV4tpYgYg6qSRkLX+Ns7fS3Q4A/ABaLLFesy1GXNMVmFNaNnUpL1KjkD2TaodbzI2AJK+BXzyFe4lO6iy2/xUxQrHLq56Dhi3Q17zjbL8ELHwTI425FFFukYRixYuOhLcv0Qy/h+SSKJs55zt574RlKG5fM4bjWxH+6qHFKyVjiVjxCB/EbYTmJWkGMFfzH527boXWm/tNTw/ASGtHte1IHt9nja9gb4MfYElKK8Z2UxXo70+k= root@bee100b2470b >> ~/.ssh/authorized_keys
