#!/usr/bin/env bash

ssh ubuntu@100.26.216.37 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6iCv3KRaLQPA4uS7RfkXsEr/tV38ZQJaNVOnrXePozR65Lg8yCkPUQoulZEPhVZc+dut2fevU8tZCkKcPOxw5BcAob4iGsft7SKxCkd57QlG0dkLed5Eqb6/X/IUX6B2oK8tlXvw8q2cGkg4WXpFwdp6XrOxpAi0gB7HGI/+Acb7vBpn1kAeESzbQRrLXec/+1NRSAZddpxUJ7moamZ8DVEEYgGZhsg5Ui+QBGi759OxVitM7i9g4jCLCEHhRFm4x+rxYozepBpxZ9Bkvo1PoQfc+avknijQJEMIm8NqvKSPvGe+mK1rp614RgCDUK0h6jFR3yN7E4CuYY5RsqSnF6yGhHt+psUehpwo/vu9z0Ho1c/GECRVBzU/o/wZbB2rdkZdiXwBQRwxEVNb4ZQpptXc0hHO4sRWfAys7gHQOMZ1lrA5z8/OfbBD1BwUK7J70HiDlWz9zMrAiRad8AhA0T+7Oa1DMAqNQoMsC4ntc8epEjHws5MeAL6U/XE/4UV8= root@03bc96889e6c >> ~/.ssh/authorized_keys
