#!/usr/bin/env bash
# creates an RSA key pair.
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# created key must be protected by the passphrase betty

ssh-keygen -f school -b 4096 -N betty -t rsa
